I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 161, in script
    commader "Это он"
Exception: Sayer 'commader' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 161, in script
    commader "Это он"
  File "renpy/ast.py", line 881, in execute
    who = eval_who(self.who, self.who_fast)
  File "renpy/ast.py", line 774, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'commader' is not defined.

Windows-10-10.0.22000 AMD64
Ren'Py 7.5.3.22090809
Alpha novella Alpha_varsion
Tue Nov  8 20:35:05 2022
